name: teamlead
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  intl:
  get: ^4.6.5
  google_fonts: 6.1.0
  font_awesome_flutter: ^10.6.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  flutter_phone_direct_caller: ^2.1.1
  flutter_email_sender: ^6.0.2
  logger: ^2.5.0
  firebase_core:
  google_sign_in: ^6.1.5
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.2
  gsheets: ^0.5.0
  share_plus: ^7.2.1
  flutter_screenutil: ^5.9.1
  device_preview: ^1.1.0
  flutter_expandable_fab: ^2.3.0
  bot_toast: ^4.1.3
  syncfusion_flutter_xlsio: ^27.2.5
  path_provider: ^2.1.4
  http: ^1.2.0
  googleapis_auth: ^1.4.0
  googleapis: ^11.4.0
  firebase_messaging:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  image_path: "images/logo1.png"

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
